application: cmbalance
version: 5
runtime: python
api_version: 1

handlers:
- url: /get/.*
  script: pages/get.py
  
- url: /mirrors
  script: pages/mirrors.py
  
- url: /rommanager
  script: pages/get.py
  
- url: /rpc
  script: pages/rpc.py
  
- url: /static
  static_dir: static

- url: /tasks/.*
  script: pages/tasks.py
  login: admin
  
- url: /
  script: pages/browse.py
